"""Added is_admin to User

Revision ID: 849d8c4f0d4b
Revises: d5599b42237d
Create Date: 2024-10-22 19:12:38.015984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849d8c4f0d4b'
down_revision = 'd5599b42237d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
