"""Añadir columna category a Product

Revision ID: bdfab73ed3ad
Revises: 849d8c4f0d4b
Create Date: 2025-02-05 23:48:15.247433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfab73ed3ad'
down_revision = '849d8c4f0d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
