"""Añadido teléfono a la tabla de reservas

Revision ID: d5599b42237d
Revises: 719d44b26651
Create Date: 2024-10-01 01:40:29.321667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5599b42237d'
down_revision = '719d44b26651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono_cliente', sa.String(length=50), nullable=False, server_default='0000000000'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('telefono_cliente')

    # ### end Alembic commands ###
